interface ResendEnv {
  RESEND_API_KEY: string;
}

function htmlEncode(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

interface SendEmailParams {
  to: string;
  subject: string;
  html: string;
  from: string;
  headers?: Record<string, string>;
}

async function sendEmail(env: ResendEnv, params: SendEmailParams): Promise<void> {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: params.from,
      to: params.to,
      subject: params.subject,
      html: params.html,
      headers: params.headers,
    }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Resend error ${res.status}: ${text}`);
  }
}

export async function sendConfirmation(
  env: ResendEnv,
  opts: {
    to: string;
    confirmUrl: string;
    siteName: string;
    fromAddress: string;
    unsubscribeUrl: string;
  },
): Promise<void> {
  await sendEmail(env, {
    to: opts.to,
    from: opts.fromAddress,
    subject: `Confirm your subscription to ${opts.siteName}`,
    html: `
      <p>Hi,</p>
      <p>Click the link below to confirm your email address and start receiving
      new job alerts from <strong>${opts.siteName}</strong>:</p>
      <p><a href="${opts.confirmUrl}">Confirm subscription</a></p>
      <p>If you didn't sign up, you can ignore this email.</p>
      <hr>
      <p style="font-size:0.85em;color:#666;">
        <a href="${opts.unsubscribeUrl}">Unsubscribe</a>
      </p>
    `,
    headers: {
      "List-Unsubscribe": `<${opts.unsubscribeUrl}>`,
      "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
    },
  });
}

export async function sendUnsubscribeAck(
  env: ResendEnv,
  opts: {
    to: string;
    siteName: string;
    fromAddress: string;
  },
): Promise<void> {
  await sendEmail(env, {
    to: opts.to,
    from: opts.fromAddress,
    subject: `You've been unsubscribed from ${opts.siteName}`,
    html: `
      <p>Hi,</p>
      <p>You've been successfully unsubscribed from <strong>${opts.siteName}</strong> job alerts.
      You won't receive any more emails from us.</p>
    `,
  });
}

export async function sendDeletionRequest(
  env: ResendEnv,
  opts: {
    /** privacy@${niche.domain} — multi-niche per RESEARCH Open Question 3 */
    to: string;
    /** The end-user's email address requesting deletion */
    requesterEmail: string;
    /** From address — typically `${siteName} <noreply@${niche.domain}>` */
    fromAddress: string;
    /** Site name (niche.name) for subject line */
    siteName: string;
  },
): Promise<void> {
  await sendEmail(env, {
    to: opts.to,
    from: opts.fromAddress,
    subject: `[GDPR] Data deletion request — ${opts.siteName}`,
    html: `
      <p>A user has requested deletion of their personal data under GDPR Article 17.</p>
      <p><strong>Requester email:</strong> ${htmlEncode(opts.requesterEmail)}</p>
      <p>Process within 30 days. Look up the email in Supabase and delete the row from the
      <code>subscribers</code> table for the matching niche schema.</p>
      <hr>
      <p style="font-size:0.85em;color:#666;">
        This notification was generated by the deletion form on /privacy of ${opts.siteName}.
      </p>
    `,
  });
}
